"""add cascade delete for cards

Revision ID: 3b3281b5422e
Revises: fc0bb435376f
Create Date: 2026-10-06 18:21:27.040205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b3281b5422e'
down_revision: Union[str, Sequence[str], None] = 'fc0bb435376f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('cards_deck_id_fkey'), 'cards', type_='foreignkey')
    op.create_foreign_key(None, 'cards', 'decks', ['deck_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cards', type_='foreignkey')
    op.create_foreign_key(op.f('cards_deck_id_fkey'), 'cards', 'decks', ['deck_id'], ['id'])
    # ### end Alembic commands ###
