"""add language native name

Revision ID: 59f1ff263589
Revises: b8fd5007323f
Create Date: 2026-10-02 13:16:11.699652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59f1ff263589'
down_revision: Union[str, Sequence[str], None] = 'b8fd5007323f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('languages', sa.Column('native_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('languages', 'native_name')
    # ### end Alembic commands ###
