"""add language owner

Revision ID: 6ed1dfd2923a
Revises: ea61a6026315
Create Date: 2026-10-01 15:47:40.378246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ed1dfd2923a'
down_revision: Union[str, Sequence[str], None] = 'ea61a6026315'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('languages', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'languages', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'languages', type_='foreignkey')
    op.drop_column('languages', 'user_id')
    # ### end Alembic commands ###
