"""add card content uniqueness

Revision ID: 945959dfcca7
Revises: 59f1ff263589
Create Date: 2026-10-03 19:58:20.318075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '945959dfcca7'
down_revision: Union[str, Sequence[str], None] = '59f1ff263589'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_card_content', 'cards', ['word', 'translation', 'language_a_id', 'language_b_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_card_content', 'cards', type_='unique')
    # ### end Alembic commands ###
