"""make language code globally unique

Revision ID: b8fd5007323f
Revises: b1bacb78de0f
Create Date: 2026-10-02 12:21:44.050411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8fd5007323f'
down_revision: Union[str, Sequence[str], None] = 'b1bacb78de0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('uq_system_language_code'), table_name='languages', postgresql_where='(user_id IS NULL)')
    op.drop_index(op.f('uq_user_language_code'), table_name='languages', postgresql_where='(user_id IS NOT NULL)')
    op.create_index('uq_language_code', 'languages', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_language_code', table_name='languages')
    op.create_index(op.f('uq_user_language_code'), 'languages', ['user_id', 'code'], unique=True, postgresql_where='(user_id IS NOT NULL)')
    op.create_index(op.f('uq_system_language_code'), 'languages', ['code'], unique=True, postgresql_where='(user_id IS NULL)')
    # ### end Alembic commands ###
