"""add user languages

Revision ID: ea61a6026315
Revises: accb6c362946
Create Date: 2026-10-01 15:00:44.466082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea61a6026315'
down_revision: Union[str, Sequence[str], None] = 'accb6c362946'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('native_language_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('learning_language_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'languages', ['native_language_id'], ['id'])
    op.create_foreign_key(None, 'users', 'languages', ['learning_language_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'learning_language_id')
    op.drop_column('users', 'native_language_id')
    # ### end Alembic commands ###
