"""replace deck card relation with direct card deck

Revision ID: fc0bb435376f
Revises: 945959dfcca7
Create Date: 2026-10-03 20:28:35.956392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc0bb435376f'
down_revision: Union[str, Sequence[str], None] = '945959dfcca7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deck_cards')
    op.add_column('cards', sa.Column('deck_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('uq_card_content'), 'cards', type_='unique')
    op.create_unique_constraint('uq_card_content', 'cards', ['deck_id', 'word', 'translation', 'language_a_id', 'language_b_id'])
    op.create_foreign_key(None, 'cards', 'decks', ['deck_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cards', type_='foreignkey')
    op.drop_constraint('uq_card_content', 'cards', type_='unique')
    op.create_unique_constraint(op.f('uq_card_content'), 'cards', ['word', 'translation', 'language_a_id', 'language_b_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('cards', 'deck_id')
    op.create_table('deck_cards',
    sa.Column('deck_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('card_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], name=op.f('deck_cards_card_id_fkey')),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], name=op.f('deck_cards_deck_id_fkey')),
    sa.PrimaryKeyConstraint('deck_id', 'card_id', name=op.f('deck_cards_pkey'))
    )
    # ### end Alembic commands ###
